- name: Prepare Steam app directory
  file:
    path: /opt/steamapp
    state: directory
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: "0755"
  become: true
  
- name: Link Steam app directory
  file:
    src: /opt/steamapp
    dest: /home/{{ target_user }}/.steam
    state: link
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: "0755"

- name: Prepare Steam userdata directory
  file:
    path: /opt/steamdata
    state: directory
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: "0755"
  become: true
  
- name: Link Steam data directory
  file:
    src: /opt/steamdata
    dest: /home/{{ target_user }}/.local/share/Steam
    state: link
    owner: "{{ target_user }}"
    group: "{{ target_user }}"
    mode: "0755"

- name: Install essential packages
  include_tasks: tasks/install_official.yaml
  loop:
  - cachyos-gaming-applications
  - protonup-qt
  loop_control:
    loop_var: package